### ISSUE TITLE
Import package to use in React

### ISSUE THREAD

**Issue by NeelakshSharma** [enepomnyaschih/byte-base64#1]
How to import your package in a React application?

**Comment by enepomnyaschih** [comment]
@NeelakshSharma - As a usual ES6 module. Install it with npm and import it with "import" ES6 syntax or "require" CommonJS function. See tests for examples https://github.com/enepomnyaschih/byte-base64/blob/master/test/src/base64ToBytes.ts

**Comment by NeelakshSharma** [comment]
Yes, i was using as a default export. I should use `import {bytesToBase64} from "byte-base64"`.
