### ISSUE TITLE
Typo mis-handling "{" characters

### ISSUE THREAD

**Issue by peaBerberian** [enepomnyaschih/byte-base64#2]
Hi,

First thanks a lot for sharing this code, it saved us some time.

I saw a small typo that leads to a (very) minor inconsistency:

Decoding the invalid "B{==" do not throw but instead returns a single byte set to `4` (same as "BA==").

My guess is that `{` is _in fine_ interpreted as a `0` (when doing bitwise thingies) because it unexpectedly passes the
```js
if (charCode > base64codes.length) {
```
check. This only happens with `{` probably because it comes just after `z` in UTF-16, the latter being the last character concerned by the `base64codes` array.

When decoding "B}==" instead, we get the expected error.

By fixing the condition to
```js
if (charCode >= base64codes.length) {
```
I have no problem anymore.

**Comment by enepomnyaschih** [comment]
Nice catch! Fixed in 1.0.2.
