### ISSUE TITLE
Change module type to ES6

### ISSUE THREAD

**Issue by francoisprunier** [enepomnyaschih/byte-base64#5]
Hello,

Thanks for your nice library!

I was wondering if you think it'd be a good idea to switch the module type in tsconfig to "es6". At the moment it's using commonjs and it's a pain to include it in systems that don't support commonjs import style (fyi I'm thinking about GraalJS, a javascript implementation on top of java).

If instead we'd output es6, we could use babel to transpile it to cjs and have both outputs available in package.json: the "main"  entry could point to the same cjs version as today and the "module" entry could point to the es6 module output.

What do you think ?

**Comment by enepomnyaschih** [comment]
Hello. What do you mean? In [tsconfig.json](https://github.com/enepomnyaschih/byte-base64/blob/master/main/tsconfig.json), target is already es6. Then follows an [extra step](https://github.com/enepomnyaschih/byte-base64/blob/master/main/build.sh) which executes Babel to transpile all ES6 syntax to one supported by the majority of browsers. Despite that, you should be able import the library using ES6 import syntax `import * as base64 from "byte-base64"` as long as you use a common bundler like WebPack or Parcel. I'm not familiar with GraalJS.

**Comment by francoisprunier** [comment]
The target is es6, but the module type is defined as commonjs: https://github.com/enepomnyaschih/byte-base64/blob/6186853e87ca74f14c63e90297b705950bb89381/main/tsconfig.json#L6

What I'm suggesting is publishing an additional file: the library as an es6 module. There's a mecanism in place for this, see this blog post: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

But in short, it means we add a `module` entry inside `package.json` that points to the file tsc outputs. The `main` entry still points to the transpiled file by babel. Note that we'd need to configure babel to transpile the es6 module format to commonjs format using a plugin like this one: https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs

**Comment by enepomnyaschih** [comment]
I've tried to do what you suggest - see the commit above. But the library stops working in IE11. Steps to reproduce:

1. Clone the repository.
2. Checkout 5-module branch.
3. In root, run npm install.
4. In "main" folder, run ./build.sh.
5. In "test" folder, run ./parcel.sh.
6. Try to open the suggested URL (e.g. http://localhost:1234) in IE11.

You'll encounter an error in the browser console, as it tries to load ES6 code. Please suggest a fix. I'll appreciate a pull request.

**Comment by francoisprunier** [comment]
Thanks, I'll have a look !

**Comment by francoisprunier** [comment]
@enepomnyaschih I've opened #6

**Comment by enepomnyaschih** [comment]
Merged and released under 1.1.0. Thank you for your contribution!
