### ISSUE TITLE
Reference other libraries

### ISSUE THREAD

**Issue by darcyparker** [enepomnyaschih/byte-base64#7]
https://github.com/enepomnyaschih/byte-base64/blame/master/README.md#L13-L15

It's good to note the limitation of `window.atob` and `window.btoa` only supporting ascii.

There are some other libraries with similarities to yours: (correct me if I am wrong)
* https://www.npmjs.com/package/base64-js (seems pretty popular when I look at weekly downloads)
* https://git.coolaj86.com/coolaj86/unibabel.js#unibabel

In your readme can you comment on these libraries?

**Comment by enepomnyaschih** [comment]
Done.
